# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c237777b29a6a04af36423340f9d1f5c919f4a9133e9310c30a1926bedaad7fac75f53376f42242516d043edfcc1726e3064d6a2aa0d8fbf6e6a0b6f65a758c0

test:
  secret_key_base: f0425a6bb15415dfec6f173ec00117058fabe633456d5531b959005ef1d8552bc049c30efb0876a61e30cee52902b311f24711c992997bac415e9fcff70ab2bb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
